### ISSUE TITLE
AAPT2 error

### ISSUE THREAD

**Issue by hadiahmadi77** [tommybuonomo/dotsindicator#10]
when I want to implement it its say AAPT2 error before building

**Comment by tommybuonomo** [comment]
Hi @hadiahmadi77,

Which version of the android gradle plugin are you using ? 

``` Gradle
dependencies {
    classpath "com.android.tools.build:gradle:???"
}
```

**Comment by hadiahmadi77** [comment]
classpath 'com.android.tools.build:gradle:3.1.3'

**Comment by tommybuonomo** [comment]
Are you using the sample from the directory or an external project ?
Can you add a stacktrace please ?

**Comment by tommybuonomo** [comment]
Duplicate of #14
