### ISSUE TITLE
how to disable click event in dot indicator

### ISSUE THREAD

**Issue by axnamit** [tommybuonomo/dotsindicator#103]
when we click in any dot in the dot indicator. it leads to me that respective page. but I don't need click event in dot indicator.I  have used  *dots_indicator.isClickable = false * but it did not worked for me

**Comment by DavidMarinov** [comment]
I have opened a PR https://github.com/tommybuonomo/dotsindicator/pull/104 for your issue it might help you out, and if the Author of this repo agrees he might merge it to the lib

**Comment by tommybuonomo** [comment]
@axnamit PR made by @DavidMarinov  has been merged and this will be available in the next release of the library.
