### ISSUE TITLE
No option to change color selected or unselected indicator

### ISSUE THREAD

**Issue by Usama75** [tommybuonomo/dotsindicator#105]
There should be option to differentiate selected and unselected color of indicator. BTW you did really good work please update this feature too or give access to add this feature Thanks.

**Comment by OverLordAct** [comment]
Yes indeed, a really nice to have feature!

**Comment by tommybuonomo** [comment]
Hello @Usama75 ,
You can already achieve this for the 3 type of indicators. 
On which one you have an issue ?
