### ISSUE TITLE
Wrong ImageView id

### ISSUE THREAD

**Issue by DupinC** [tommybuonomo/dotsindicator#11]
Hello, the id of the ImageView :
https://github.com/tommybuonomo/dotsindicator/blob/5594d50800f31f6dd1293b83be607095863ac56d/viewpagerdotsindicator/src/main/java/com/tbuonomo/viewpagerdotsindicator/WormDotsIndicator.java#L161

should be

https://github.com/tommybuonomo/dotsindicator/blob/5594d50800f31f6dd1293b83be607095863ac56d/viewpagerdotsindicator/src/main/res/layout/worm_dot_layout.xml#L9

**Comment by DupinC** [comment]
Same error on 

https://github.com/tommybuonomo/dotsindicator/blob/master/viewpagerdotsindicator/src/main/java/com/tbuonomo/viewpagerdotsindicator/SpringDotsIndicator.java

**Comment by tommybuonomo** [comment]
Hi @DupinC ,

Well spotted !

**Comment by DupinC** [comment]
Thanks, do you plan to release a new version with the fix soon ?

**Comment by tommybuonomo** [comment]
@DupinC fixed ;)

**Comment by DupinC** [comment]
Thanks ! But I've spotted another issue : #13  :/
