### ISSUE TITLE
Request option to setMaxDotCount

### ISSUE THREAD

**Issue by alanlai1989** [tommybuonomo/dotsindicator#111]
if this method not calling or setting, the default maxDotCount should be total of viewpager items

use case 1:
setMaxDotCount(4);
if total viewpager items got 10, the dot will show max dot count (4)

use case 2:
if total viewpager items got 10, the dot will show max dot count (10)

use case 3:
setMaxDotCount(4);
if total viewpager items got 3, the dot will show max dot count (3)

**Comment by tommybuonomo** [comment]
Hello @alanlai1989 
I don't understand exactly your needs here.
If there is 10 page in your view pager with `setMaxDotCount(4)`, what's the display for the 5th page ?

**Comment by alanlai1989** [comment]
sorry, for very late reply. 
If there is 10 page in your view pager with setMaxDotCount(4), what's the display for the 5th page ?
5th one selected and the hightlighted dot should be at third point until 9th position. When scrolling to last item then the highlighted dot should move to last one.
@tommybuonomo
