### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kasmadi17** [tommybuonomo/dotsindicator#113]

**Comment by kasmadi17** [comment]
> Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
> length=15; index=-26
> com.tbuonomo.viewpagerdotsindicator.DotsIndicator$buildOnPageChangedListener$1.onPageScrolled$viewpagerdotsindicator_release (DotsIndicator.java:107)
> com.tbuonomo.viewpagerdotsindicator.OnPageChangeListenerHelper.onPageScrolled (OnPageChangeListenerHelper.java:22)

**Comment by joshminton** [comment]
I'm also experiencing this issue. Did you find a fix for it or something?

**Comment by kasmadi17** [comment]
i thing this issue about reloading content. i can't fix this issue
