### ISSUE TITLE
Migrate away from JCenter

### ISSUE THREAD

**Issue by steffandroid** [tommybuonomo/dotsindicator#115]
[JFrog](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) has just announced that it will be shutting down JCenter on May 1st. JCenter is the sole repository hosting this library, so it will become unavailable after this date unless migrated to an alternative service.

**Comment by tommybuonomo** [comment]
Hello @steffandroid 
I am currently doing the migration to the library on maven central
Thanks for the feedback

**Comment by steffandroid** [comment]
Awesome! Thanks for the confirmation.

**Comment by Areyana** [comment]
Any news about migration ?

**Comment by tommybuonomo** [comment]
Hello there, 
The library is now available on maven central:
`implementation 'com.tbuonomo:dotsindicator:4.2'`
Sorry for the late :)
