### ISSUE TITLE
How can I reduce dotsWithFactor in DotsIndicator

### ISSUE THREAD

**Issue by AhmedElsayedTaha** [tommybuonomo/dotsindicator#122]
I hope someone answer me 
I can't reduce the size of the selected dot in the DotsIndicator , How can I reduce its size (dots with factor )
It's by default 2.5 .. when I write a number less than 2.5 it doesn't reduce 

![image](https://user-images.githubusercontent.com/49143167/112889571-1682bd00-90d6-11eb-9c99-4c424125ba4d.png)

 ```
<com.tbuonomo.viewpagerdotsindicator.DotsIndicator
                android:id="@+id/dots_indicator"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:layout_marginTop="5dp"
                app:dotsColor="#34340023"
                app:dotsCornerRadius="@dimen/_100sdp"
                app:dotsSize="@dimen/_8sdp"
                app:dotsSpacing="4dp"
                app:dotsWidthFactor="0.0"
                app:selectedDotColor="#340023"
                />
```

**Comment by tommybuonomo** [comment]
Hello @AhmedElsayedTaha the `dotsWidthFactor` attribute can't be under 1.0, that's why it does not change
