### ISSUE TITLE
Please Migrate ASAP 

### ISSUE THREAD

**Issue by NotNotMarshall** [tommybuonomo/dotsindicator#123]
jCenter is currently deprecated and artifacts can only be downloaded till 2022-02-01, consider migrating to jitpack or maven central.
more info here:
https://developer.android.com/studio/build/jcenter-migration

**Comment by migos** [comment]
No worries, it will be "read-only ... indefinitely" (https://twitter.com/steveonjava/status/1387072410868797440) but yeah, for updates the lib should/must be migrated.

**Comment by scottdweber** [comment]
I believe that has been addressed in version 4.2. See #115
