### ISSUE TITLE
Set number of dots..

### ISSUE THREAD

**Issue by DevX-cmd** [tommybuonomo/dotsindicator#127]
Hello everyone. I am using this library for an app. I want to only implement 3 dots.. By default there are 5 dots. How can i do that..

**Comment by divyabyte** [comment]
Hello, It will automatically detect the number of fragments your view pager has. And according to that number of dots will be displayed.

**Comment by tommybuonomo** [comment]
Thanks @divyabyte for your perfect answer
Closing this now 🙏
