### ISSUE TITLE
removeDot method

### ISSUE THREAD

**Issue by BrayanMC** [tommybuonomo/dotsindicator#130]
Hello, how are you? why the abstract method `removeDot(index: Int)` has a parameter when this never is used.

<img width="555" alt="Captura de Pantalla 2021-06-30 a la(s) 17 02 26" src="https://user-images.githubusercontent.com/7269320/124037323-f9a3a180-d9c4-11eb-8cde-9018c3d843f1.png">

**Comment by tommybuonomo** [comment]
Hello @BrayanMC thanks for your contribution, this will be fixed in the next version
