### ISSUE TITLE
Runtime Error when inflating SpringDotsIndicator

### ISSUE THREAD

**Issue by KnightFiury** [tommybuonomo/dotsindicator#134]
![Screenshot_20211015-114212](https://user-images.githubusercontent.com/86944710/137488820-5d2910ea-bb50-4076-ab7f-5aaf29755c3c.png)

**Comment by superdiazzz** [comment]
I have same issue in crashlytics,

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{mobile.android.tribun/com.my.app.IntroActivity}: android.view.InflateException: Binary XML file line #30: Binary XML file line #30: Error inflating class com.tbuonomo.viewpagerdotsindicator.SpringDotsIndicator`

It is pointing to SpringDotsIndicator in xml file. Have solved this issue?

**Comment by tommybuonomo** [comment]
Hello @superdiazzz, it looks like an error in your own project
Do you have more info on the stack trace ? Without more info, I'll close this issue
