### ISSUE TITLE
Can the selected dot have a gradient background?

### ISSUE THREAD

**Issue by CosminCirlea** [tommybuonomo/dotsindicator#138]
Hello!
I'm trying to make the selected dot have a gradient background and I can't find an easy way of doing so. Is it possible? If so, please help!

**Comment by tommybuonomo** [comment]
Hello @CosminCirlea 
Sorry but it's not possible and we don't plan to have this behavior
Feel free to fork the repo and make the necessary modifications to achieve your custom request 🙂
