### ISSUE TITLE
Error:(9, 5) error: resource android:attr/dialogCornerRadius not found.

### ISSUE THREAD

**Issue by milindrc** [tommybuonomo/dotsindicator#14]
Error:(9, 5) error: resource android:attr/dialogCornerRadius not found.
Error:(1234, 5) error: resource android:attr/fontVariationSettings not found.
Error:(1234, 5) error: resource android:attr/ttcIndex not found.

**Comment by mrparoli** [comment]
Downgrade to 2.0.0 work for me (please fix for 2.1.1)

**Comment by milindrc** [comment]
that didn't work to.


On 27-Jul-2018 3:42 PM, mrparoli <notifications@github.com> wrote:

Downgrade to 2.0.0 work for me (please fix for 2.1.1)

**Comment by tommybuonomo** [comment]
Hi @milindrc, @mrparoli,

The library is targeting android P with compileSdkVersion to 28.

Can you upgrade your project ? (currently 27 I guess)

**Comment by milindrc** [comment]
Yes I was using 27, updating it to 28 worked, thanks. But isn’t the minimum requirements for this library too high?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tommybuonomo** [comment]
It's not the minimum (16) but the support version must match

**Comment by Sarat-1997** [comment]
@tommybuonomo I had upgraded compilesdk version to 34 and added  implementation 'com.tbuonomo:dotsindicator:5.0' in build.gradle(app), still corner radius not found occurs. The following xml file code below:

  <com.tbuonomo.viewpagerdotsindicator.DotsIndicator
            android:id="@+id/dots_indicator"
            android:layout_width="wrap_content"
            android:layout_height="0dp"
            app:dotsColor="@color/colorAccent"
            app:dotsCornerRadius="8dp"
            app:dotsSize="16dp"
            app:dotsSpacing="4dp"
            app:dotsWidthFactor="2.5"
            app:selectedDotColor="@android:color/holo_red_dark"
            app:progressMode="true"
            android:layout_marginStart="8dp"
            app:layout_constraintStart_toStartOf="parent" android:layout_marginLeft="8dp" android:layout_marginEnd="8dp"
            app:layout_constraintEnd_toEndOf="parent" android:layout_marginRight="8dp"
            android:layout_marginBottom="16dp"
            app:layout_constraintBottom_toBottomOf="parent"/>
            
            
            All the elements are present here but how cornerradius not found occur? Kindly reply ASAP.
