### ISSUE TITLE
SpringDotsIndicator set dots Stroke Width programmatically

### ISSUE THREAD

**Issue by saeed74** [tommybuonomo/dotsindicator#144]
I can't find the ` indicator.setdotsStrokeWidth()` method in SpringDotsIndicator Class, is this possible?

**Comment by tommybuonomo** [comment]
Hello, thanks for your contribution !
This issue is now fixed in the new version `4.3`
Thanks 🔥

**Comment by kose-cansu** [comment]
I cant write setDotCount and setCurrentPosition
