### ISSUE TITLE
cant applied staging env

### ISSUE THREAD

**Issue by rahmativan** [tommybuonomo/dotsindicator#164]
Execution failed for task ':app:dataBindingMergeDependencyArtifactsStaging'.
> Could not resolve all files for configuration ':app:stagingCompileClasspath'.
   > Could not resolve com.tbuonomo:dotsindicator:4.3.

**Comment by avocadochif** [comment]
@rahmativan faced with the same problem, did you find solution?

**Comment by rahmativan** [comment]
> @rahmativan faced with the same problem, did you find solution?

I found the solution with downgrade version with 4.2 and with stagingImplementation in gradle

**Comment by rohitPagare** [comment]
> > @rahmativan faced with the same problem, did you find solution?
> 
> I found the solution with downgrade version with 4.2 and with stagingImplementation in gradle

Thank you buddy, its working **dotsIndicator.setViewPager2(viewpager2)**
