### ISSUE TITLE
No build variant found for ':app'

### ISSUE THREAD

**Issue by Axhillex** [tommybuonomo/dotsindicator#174]
I am trying to implement the dots indicator in my project but I am constantly getting this error.
Gradle -> 7.5
Kotlin -> 1.7.10
core-ktx -> 1.8.0
dotsIndicator -> 5.0
Project JVM -> 11
compile option -> JavaVersion.Version_1_8
jvmTarget -> 1.8
gas services -> 4.3.10
android application -> 7.3.1

Any help regarding this?? I don't have any variants for my app all I have is debug and release variants. Any was to workaround this or solve this? Much appreciated thanks.

**Comment by tommybuonomo** [comment]
Need more info
