### ISSUE TITLE
When the view with the viewpager is created a dot is seen as below the other dots

### ISSUE THREAD

**Issue by createS0ftware** [tommybuonomo/dotsindicator#19]
When the view with the viewpager is created a dot is seen as below the other dots. 

Can you replicate this ? Can you fix it ?

Thanks

**Comment by tommybuonomo** [comment]
Hi @createS0ftware,
I can't replicate this behavior. Can you provide a video or a gif?

**Comment by createS0ftware** [comment]
Sorry i was working on something else. Back to this now - i changed the layout and it seems to have stopped but i have another problem - when i have 2 or more items in a viewpager , the dotsindicator shows up with 3 dots

**Comment by createS0ftware** [comment]
I'm going to open a new issue
