### ISSUE TITLE
Could not resolve com.tbuonomo:dotsindicator:5.0.

### ISSUE THREAD

**Issue by Ven03656** [tommybuonomo/dotsindicator#192]
Variant 'debugVariantMavenApiPublication' capability com.tbuonomo:dotsindicator:5.0:
              - Incompatible because this component declares a component for use during compile-time, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component for use during runtime, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'stagging'

**Comment by Iftekhar29** [comment]
so what is a solution for that?  @tomkricensky

**Comment by Iftekhar29** [comment]
@tommybuonomo please update your library with given suggestion.

**Comment by tommybuonomo** [comment]
On it

**Comment by unzila-zafar** [comment]
hello which version of your library is working in android?

**Comment by tommybuonomo** [comment]
Hello there, it should now be fixed with the latest version `5.1.0`
