### ISSUE TITLE
Could not find com.tbuonomo.andrui:viewpagerdotsindicator:4.1.2.

### ISSUE THREAD

**Issue by Akshayck-dev** [tommybuonomo/dotsindicator#197]
![image](https://github.com/user-attachments/assets/b1a21cb6-91f2-4e15-8a56-a936c09d9742) @tommybuonomo

**Comment by goldfish07** [comment]
Fix https://github.com/tommybuonomo/dotsindicator/issues/115 The library is now on MavenCentral. 
The library name moves from `com.tbuonomo.andrui:viewpagerdotsindicator` to `com.tbuonomo:dotsindicator`

> repositories {
    google()
    mavenCentral()
}
dependencies {
    implementation("com.tbuonomo:dotsindicator:5.0")
}

**Comment by khengyun** [comment]
> Fix #115 The library is now on MavenCentral. The library name moves from `com.tbuonomo.andrui:viewpagerdotsindicator` to `com.tbuonomo:dotsindicator`
> 
> > repositories {
> > google()
> > mavenCentral()
> > }
> > dependencies {
> > implementation("com.tbuonomo:dotsindicator:5.0")
> > }

many thanks
