### ISSUE TITLE
Indicator stroke and fill doesn't match

### ISSUE THREAD

**Issue by iamMehedi** [tommybuonomo/dotsindicator#22]
I am using the WormsDotIndicator

```xml
<com.tbuonomo.viewpagerdotsindicator.WormDotsIndicator
                android:id="@+id/pager_indicator"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                app:dotsColor="@color/pink"
                app:dotsStrokeColor="@color/lessPink"
                app:dotsCornerRadius="10dp"
                app:dotsSize="10dp"
                app:dotsSpacing="6dp"
                app:dotsWidthFactor="2.5"
                />
```
When on the last page the filled dot seems to be a bit out of the stroke circle

<img width="242" alt="screenshot 2019-01-03 at 8 03 47 pm" src="https://user-images.githubusercontent.com/3691635/50641876-91121000-0f93-11e9-91e0-c1546b659e71.png">

**Comment by tommybuonomo** [comment]
Hi @iamMehedi,

I don't really know what you mean, do you say that the filled circle is bigger than the other stroke circles only on the last page ?

Can you provide another picture with best quality please ?

**Comment by iamMehedi** [comment]
I mean that the filled pink circle isn't perfectly inside the empty stroke circle. For example this is how it should be:
<img width="360" alt="screenshot 2019-01-03 at 9 20 25 pm" src="https://user-images.githubusercontent.com/3691635/50645373-9f652980-0f9d-11e9-9505-561eab541a08.png">

But for the last dot this looks like this (there's 2 dots on the let of filled circle)
<img width="513" alt="screenshot 2019-01-03 at 9 20 02 pm" src="https://user-images.githubusercontent.com/3691635/50645430-bd328e80-0f9d-11e9-9fe0-94ae2afd4da8.png">

**Comment by tommybuonomo** [comment]
Hi @iamMehedi,
Can you please try with the last version `4.0` ?
Thanks
