### ISSUE TITLE
SpringDotsIndicator and dotsindicator and wormdotsindicator doesnt appear on the screen 

### ISSUE THREAD

**Issue by porya74** [tommybuonomo/dotsindicator#24]
All three types of indicators never appear on the screen.
implementing according to the git doc.
xml and java files attached here.
[indicators.zip](https://github.com/tommybuonomo/dotsindicator/files/2793877/indicators.zip)

**Comment by tommybuonomo** [comment]
@porya74 you can't just said "It's not working", I need more information.
If you clone the project and start the sample app, you'll see that is working fine.
I'll close the pull request if you don't want to help more.

**Comment by tommybuonomo** [comment]
Sorry @porya74 , but this is not the implementation according to thee git doc. 

You set the `layout_width` and `layout_height` to `30dp` in your XML file for the SpringDotsIndicator. Put them to `wrap_content` and tell me if it's work.

**Comment by porya74** [comment]
yeah.
I tested it before by different values. but didnt work.

**Comment by tommybuonomo** [comment]
Can you provide the implementation of your adapter?

**Comment by porya74** [comment]
Adpater for what?
ViewPager?

**Comment by tommybuonomo** [comment]
Is it working now?

**Comment by porya74** [comment]
yeah.
this is a Screenshot form emulator and the java file of adapter.
[adapter.zip](https://github.com/tommybuonomo/dotsindicator/files/2793975/adapter.zip)

**Comment by porya74** [comment]
according to the xml codes the indicator must be appeared below the viewPager on the white space.
but there is nothing there as you see.

**Comment by porya74** [comment]
you have shared cool repos dude
I like them all.

**Comment by tommybuonomo** [comment]
@porya74 sorry but you have to handle this yourself, I'm sure that your layout is malformed somewhere, and I'm sure you will find the solution.
Maybe colors, maybe wrong width or height, but not the fault of the library.
By the way, you're welcome.

**Comment by porya74** [comment]
I found the solution.
I forgot to cast indicator when initialize in the java code, because I didnt think it may be necessary since it is'nt necessary in new versions of android studio.
the  initialization should be like this:
dotsIndicator = (SpringDotsIndicator) findViewById(R.id.dots_indicator);
