### ISSUE TITLE
Use rectangle icon?

### ISSUE THREAD

**Issue by bansarie10** [tommybuonomo/dotsindicator#29]
Is there a way to use square/rectangle icon instead of circle? Any help would be appreciated. Thanks!

**Comment by tommybuonomo** [comment]
Hi @bansarie10,

You can achieve this by putting the 
`dotsCornerRadius` to 0dp.

**Comment by bansarie10** [comment]
Thanks, that works. I should have been clear though, I actually want to implement it as shown in the image. 
<img width="195" alt="screen shot 2019-02-24 at 1 55 41 am" src="https://user-images.githubusercontent.com/6386625/53297779-25506480-37d8-11e9-9ec6-5b97f0537031.png">

when I restrict height to say, `10dp`, but give bigger dotSize.
`app:dotsSize="36dp"`
it works but only on some phones. Others look pretty bad, which is expected. Any thoughts around achieving this? Thank you.

**Comment by DroidLove** [comment]
@bansarie10 Did you got the solution for your use case? I need some similar solution.

**Comment by bansarie10** [comment]
@DroidLove sorry, not yet! I am waiting for response from @tommybuonomo :)

**Comment by tommybuonomo** [comment]
Hi @DroidLove , @bansarie10,
The dots have a squared size, they are not intended to have a width size different of the height size.
This behavior should reconsider all computation of the indicator classes, and this is not planned for today, unless many people ask for this case.

Good day to both of you :)

**Comment by Spettacolo83** [comment]
I need this too! Can you implement this please?
