### ISSUE TITLE
Resetting dot indicator to position 0

### ISSUE THREAD

**Issue by doumodiop** [tommybuonomo/dotsindicator#31]
Hello,

I am using your library in order to do a pop up screen containing a stepper in my android application.

I am able to close pop up whatever step I am. 
if I click to a close icon, I collapse my pop up screen and I reset my view pager to beginning( to index zero).

When I open again my pop up screen,  viewpager is correctly to first step but I have two dots with active color.
How can I reset the active dot first one when I resetting the viewpager to the beginning in the same time?

**Comment by tommybuonomo** [comment]
Hi @doumodiop, 

What do you mean by "I reset my view pager to beginning( to index zero)" ?

**Comment by PranjalDS** [comment]
When I call notifyDataSetChanged() , the dot reset to initial position.

**Comment by tommybuonomo** [comment]
@doumodiop @PranjalDS Can you pease try with the last version `4.0` ?
Thanks
