### ISSUE TITLE
RTL not working (view isn't visible)

### ISSUE THREAD

**Issue by Shailevy** [tommybuonomo/dotsindicator#32]
I'm using the WormDotsIndicator
My App is only in English but I have supportRtl=true in my manifest

When the device is in an RTL language the the view isn't visible (Although I can see it's taking the correct space when I do "Show layout bounds" on the device

**Comment by kar** [comment]
I can confirm this. I can only see one dot, and it's not animating at all.

**Comment by MohamedMohy9192** [comment]
I have the same problem ??

**Comment by Shailevy** [comment]
If the layout direction isn't a bug issue you can add android:layoutDirection="LTR" for the layout holding the dots
If that isn't an option for you I suggest you fork the the library or fix it or use a different library .. unfortunately  this issue is open for some time now

**Comment by midhilaj-flutter-developer** [comment]
I am using SpringDotsIndicator and in rtl it is not working

**Comment by AliElDerawi** [comment]
> If the layout direction isn't a bug issue you can add android:layoutDirection="LTR" for the layout holding the dots
> If that isn't an option for you I suggest you fork the the library or fix it or use a different library .. unfortunately this issue is open for some time now

This solution fixes the issue, though it's not perfect, thanks for sharing.

**Comment by tommybuonomo** [comment]
Hi everybody,
Can someone try again with the last version `4.0` please.
Thanks

**Comment by abdulmuttaleb** [comment]
Still persists.

**Comment by tommybuonomo** [comment]
Hi everybody,
Can you please try with the new version `4.1` ?
Thanks

**Comment by Sabboo** [comment]
> Hi everybody,
> Can you please try with the new version `4.1` ?
> Thanks

I have tried it with version (4.1.2) and now its working fine. But a new problem arises because the method `fun setViewPager(viewPager: ViewPager)` only accepts ViewPager and it still not consistent with rtl mode. Google introduced ViewPager2 to solve these problems. So currently its working fine but only with ViewPager and its showing a reversed direction animation for the dots.

**Comment by tommybuonomo** [comment]
@Sabboo you have now the support of ViewPager2 using the method `setViewPager2` instead of `setViewPager`

**Comment by Sabboo** [comment]
@tommybuonomo Ah I didn't notice that, everything is working fine now.
Thanks.
