### ISSUE TITLE
findViewById, causing missing adapter error

### ISSUE THREAD

**Issue by DiogoTheCoder** [tommybuonomo/dotsindicator#37]
When I execute `DotsIndicator dotsIndicator = findViewById(R.id.dots_indicator_view_pager_insights);`, getting an error message straight away

`DotsIndicator: You have to set an adapter to the view pager before !`

I do set the adapter right after the `findViewById`, shouldn't the message appear later on, if no adapter has yet been set?

**Comment by tommybuonomo** [comment]
Hi @DiogoTheCoder,
You have to set an adapter to the view pager before setting the view pager to the dots indicator.

**Comment by DiogoTheCoder** [comment]
Hi @tommybuonomo 
I believe I am currently setting the adapter to the view pager first, then the dots indicator.

Example:
```
DotsIndicator dailyNutrientsInsightsDotsIndicator = findViewById(R.id.dots_indicator_view_pager_nutrients_insights);

dailyNutrientsInsightsViewPager.setAdapter(dailyNutrientsInsightsPageAdapter);
dailyNutrientsInsightsDotsIndicator.setViewPager(dailyNutrientsInsightsViewPager);
```

**Comment by whostherichest** [comment]
Are you sure that your `dailyNutrientsInsightsPageAdapter` is not null at this point ?

**Comment by tommybuonomo** [comment]
Are you sure that your `dailyNutrientsInsightsPageAdapter` is not null at this point ?

**Comment by DiogoTheCoder** [comment]
Just checked and according to the debugger, it isn't equal to null.

![image](https://user-images.githubusercontent.com/31896387/55386848-43705980-5528-11e9-9daf-7ff7389baedd.png)

**Comment by tommybuonomo** [comment]
Sorry but the code is clear:
```Java
if (viewPager != null && viewPager.getAdapter() != null) {
      ...
    } else {
      Log.e(DotsIndicator.class.getSimpleName(), "You have to set an adapter to the view pager before !");
    }
```

You have an error somewhere in your code.

**Comment by Selidinok** [comment]
I have similar issue. DotsIndicator call refreshDots() inside init(AttributeSet attrs) method when class initialize. So even viewPager = null at that moment.
