### ISSUE TITLE
Performance issue/leak causing crash

### ISSUE THREAD

**Issue by mgj** [tommybuonomo/dotsindicator#4]
I have used this in an app where i update the adapter in OnResume(). I navigate between the main activity and another activity, and back again. Without the dotsindicator, everything is fine. 

When i add the dotsindicator, i hit a performance issue which gets worse and worse the more times i call adapter.notifyDataSetChanged(). Using the android performance profiler i can see that the DotsIndicator is calling setUpDots() over and over again.

Like i said the problem becomes worse and worse the more times i call adapter.notifyDataSetChanged() untill the app finally crashes.

![1](https://user-images.githubusercontent.com/1054499/32812434-3aa45082-c9a5-11e7-9ac2-ea97d5bcc672.PNG)
![2](https://user-images.githubusercontent.com/1054499/32812435-3abb4bfc-c9a5-11e7-8f31-d55d7a52d117.PNG)

**Comment by tommybuonomo** [comment]
Hi @mgj !
This leak was caused by a method called in loop for the indicator dots setup. Thanks for noticing !
The issue is now fixed on version 1.1.0
