### ISSUE TITLE
How to disable click on dotIndicator ?

### ISSUE THREAD

**Issue by gabriel-TheCode** [tommybuonomo/dotsindicator#43]
I'm trying to disable the click on the DotIndicator so that the viewpager does not swipe anymore when I click on the dot. Help please !

**Comment by tommybuonomo** [comment]
Hi @gabriel-TheCode ,
You have a `setDotsClickable(boolean dotsClickable)` method

**Comment by gabriel-TheCode** [comment]
Thanks !
