### ISSUE TITLE
Resize automatically

### ISSUE THREAD

**Issue by developerGM** [tommybuonomo/dotsindicator#45]
I am using `SpringDotsIndicator` but in my gallery I have more then 20 images and the dots doesn't resize automatically.
Any solutions?

I tried to add `SpringDotsIndicator` inside an horizontal `ScrollView` but nothing.

**Comment by developerGM** [comment]
You should use a Flexbox-layout.
https://github.com/google/flexbox-layout

**Comment by tommybuonomo** [comment]
Hi @developerGM,
I can't use a flex box in this case because the dots size and location are computed in the dots indicator view.
However, resizing automatically is a great feature in this case.
I'll implement it manually :wink:

**Comment by VGJohn** [comment]
Hi @tommybuonomo, glad to see you're going to address this issue 😁
If the view pager had say 50 or 100 items, how are you planning on handling this case without the dots resizing to be too small.

**Comment by fernandobracaroto** [comment]
So this lib is only useful if there is only 6 os less itens?
