### ISSUE TITLE
Support Indicator for the RecyclerView.

### ISSUE THREAD

**Issue by Harsh2402** [tommybuonomo/dotsindicator#47]
Is there any way to set the indicator according to the recycler view?

**Comment by tommybuonomo** [comment]
@Harsh2402 Hi,
No you can't, but starting from the version `4.0`, you can now use ViewPager2 instead of ViewPager.

**Comment by RahulSDeshpande** [comment]
> Is there any way to set the indicator according to the recycler view?

In fact, we can!
But you need to **manually handle the horizontal scrolling of the indicator items depending upon the scrolling of the `RecyclerView` items**, for which usage of `SpanHelper` is must.

Try it out & do let us know :)
