### ISSUE TITLE
Support for large number of view pager items

### ISSUE THREAD

**Issue by VGJohn** [tommybuonomo/dotsindicator#48]
Currently the worm dot indicator gets cut off at the end if there are more view pager items then can fit in the width of the dot indicator. Can you wrap the dots or maybe stay on the middle dot until it make sense to start scrolling to the last dot again?

**Comment by tommybuonomo** [comment]
Duplicate of #45

**Comment by KoTius** [comment]
@tommybuonomo Hey. Could you please hint how the issue is resolved?
