### ISSUE TITLE
Click bug

### ISSUE THREAD

**Issue by Tijn1314** [tommybuonomo/dotsindicator#49]
DotsIndicator ----> interval clicks  dots width  bug

**Comment by Tijn1314** [comment]
public abstract class OnPageChangeListenerHelper implements ViewPager.OnPageChangeListener {
    private int currentPage;
    private int lastPage;
    private int lastSelected;

    @Override
    public final void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
        int selectedPosition = currentPage;


        resetPosition(lastSelected);
        if ((position != currentPage && positionOffset == 0) || currentPage < position) {
            resetPosition(currentPage);
            selectedPosition = currentPage = position;
        }

        if (Math.abs(currentPage - position) > 1) {
            resetPosition(selectedPosition);
            selectedPosition = currentPage = lastPage;
        }

        int nextPosition = -1;
        if (currentPage == position && currentPage + 1 < getPageCount()) {
            nextPosition = currentPage + 1;
        } else if (currentPage > position) {
            nextPosition = selectedPosition;
            selectedPosition = currentPage - 1;
        }
        Log.d("onPageScrolled1", selectedPosition + "," + nextPosition);
        Log.d("onPageScrolled2", currentPage + "," + position);
        onPageScrolled(selectedPosition, nextPosition, positionOffset);

        lastPage = position;
    }

    @Override
    public final void onPageSelected(int position) {
        currentPage = position;
        Log.d("onPageSelected", currentPage + "," + lastPage);
        lastSelected = lastPage;
    }

    @Override
    public final void onPageScrollStateChanged(int i) {

    }

    abstract void onPageScrolled(int selectedPosition, int nextPosition, float positionOffset);

    abstract void resetPosition(int position);

    abstract int getPageCount();
}

**Comment by tommybuonomo** [comment]
@Tijn1314 Hi, can you please try with the last version `4.0` ?
Thanks
