### ISSUE TITLE
Can you provide RTL orientation in your indicator?

### ISSUE THREAD

**Issue by shaheenzahedi** [tommybuonomo/dotsindicator#5]

**Comment by tommybuonomo** [comment]
Hi @shaheenzahedi !
The RTL orientation is now available on version 1.1.0

**Comment by hchouhan02** [comment]
Hi @tommybuonomo, It's not working properly in RTL mode. Please check attached images.

In English mode:
![image](https://user-images.githubusercontent.com/2250979/50784978-4ff06780-12d5-11e9-83eb-be19787d7b46.png)

In Arabic mode:
![image](https://user-images.githubusercontent.com/2250979/50785005-626aa100-12d5-11e9-8ec3-84138908d45c.png)

Thanks

**Comment by tommybuonomo** [comment]
Hello @hchouhan02,

Can you test again with the version **3.0.3** ?

Thanks.

**Comment by chiragsheta** [comment]
It's still not working
Please check Screenshots
![device-2019-08-06-142014](https://user-images.githubusercontent.com/10400295/62525805-adda3300-b855-11e9-8b63-b4eefb476865.png)
![device-2019-08-06-142051](https://user-images.githubusercontent.com/10400295/62525808-adda3300-b855-11e9-8927-d81e301d8059.png)
