### ISSUE TITLE
How do I increate the size of unselected dots?

### ISSUE THREAD

**Issue by chnouman** [tommybuonomo/dotsindicator#53]
I'm trying to increasing the size of unselected dots little bit almost half of selected dot. Can you please share me the way to do this?

**Comment by tommybuonomo** [comment]
Hi @chnouman, 
I don't really visualize the UI of your request here, can you share a sketch ?
Thanks

**Comment by chnouman** [comment]
I want to increase the size of grey icons like their width. It is currently less than half of the white dot but I need to increase it's size. 

<img width="72" alt="dost" src="https://user-images.githubusercontent.com/15146352/65695826-af73ea80-e091-11e9-98cf-4c7ed8720137.PNG">

**Comment by zigaboba** [comment]
did you find a solution to the problem?
