### ISSUE TITLE
[BUG] Is possibile to have few selected dots

### ISSUE THREAD

**Issue by Heroes84** [tommybuonomo/dotsindicator#59]
Hey, thanks for nice library ! I have some feature request:
I want have support for android.support.v4.view.ViewPager, not everbody and the moment use androidX.
Second I found bugs see screen below:
![github-bug](https://user-images.githubusercontent.com/5124243/65245796-8f6e8500-daed-11e9-91b0-99cf1cf22d16.PNG)

As you can see I have two items that have `selectedDotColor`, selected dots may showed at random position:
![indicator-bug](https://user-images.githubusercontent.com/5124243/65307913-318f7b00-db89-11e9-8a64-9de4bf27b5e2.png)

**Comment by tommybuonomo** [comment]
Hi @Heroes84 What version of the library you used to reproduce this issue ?

**Comment by Heroes84** [comment]
I used the newested available version.

**Comment by tommybuonomo** [comment]
Hello, thanks for your contribution !
This issue is now fixed in the new version `4.3`
Thanks 🔥
