### ISSUE TITLE
Dots : Random Size when looping banner

### ISSUE THREAD

**Issue by ghost** [tommybuonomo/dotsindicator#66]
Hi, thankss for this Awesome Library, i love it :D, 
hi dev i have issue when looping banner with ViewPager + DotsIndicator....

in my case, for example i have 10 banner auto looping, and when reaching last banner , viewPager set banner position to 0 again, and the issue coming, Dots Size are become randomizing sized after the last banner....

![Untitled](https://user-images.githubusercontent.com/19769273/69226324-8ca61400-0bb2-11ea-8f02-5d5f933cf423.png)

im sorry for my broken english :D

**Comment by tommybuonomo** [comment]
Hi @odlsoon, are you Suze that you're using the last version 4.1.2?

**Comment by odlsoon** [comment]
@tommybuonomo thanks for response :D, sorry, im forgot about write the version, im using version 3.0.3 because, still using AppCompat instead of AndroidX

**Comment by walixiwa** [comment]
I meet the same problem,the indicator always skip first position.
I'm using the version 4.2
![QQ图片20210815005054](https://user-images.githubusercontent.com/48165620/129453541-1849fcc1-d49e-4fa2-b71b-0c7d58aceb0b.jpg)

**Comment by walixiwa** [comment]
i meet the problem in loop viewpager2

**Comment by tommybuonomo** [comment]
Hey I succeeded to make it work with this piece of code using the last version of the library (`4.3`)
```Kotlin 
fun triggerNextPageDelayed() {
    Handler().postDelayed({
        val nextItem = if (viewPager2.currentItem == adapter.itemCount - 1) {
            0
        } else {
            viewPager2.currentItem + 1
        }
        viewPager2.currentItem = nextItem
        triggerNextPageDelayed()
    }, 500)
}
triggerNextPageDelayed()
```
