### ISSUE TITLE
2 stupid questions (sorry :) )

### ISSUE THREAD

**Issue by MadRatSRP** [tommybuonomo/dotsindicator#69]
1)How can i make them take square form?
2)How to centerize them in view? without padding

**Comment by DavidUps** [comment]
1 -> app:dotsCornerRadius="0dp"
2 :
-  android:layout_width="wrap_content"
-  app:layout_constraintLeft_toLeftOf="parent"
-  app:layout_constraintRight_toRightOf="parent"
