### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mjesar** [tommybuonomo/dotsindicator#7]
cant find this ViewPagerAdapder

**Comment by tommybuonomo** [comment]
Hi @mjesar ,
The library only focuses on the point below the view pager. That said, your comment is not useless. I will add an example project in the repository to better understand its use.

Thanks for your feedback.

**Comment by mjesar** [comment]
thank you for your answer and i figure out that how it work in my code and it works fine perfect 
Thank you good job

**Comment by tommybuonomo** [comment]
@mjesar the sample folder is now in the repository. You can find the adapter I made for the sample.
Best regards !
