### ISSUE TITLE
How to set the dotIndicator point position 2 when viewPager2 currentItem = 2

### ISSUE THREAD

**Issue by lic2050** [tommybuonomo/dotsindicator#72]
viewPager2.setCurrentItem(2, false)
dotIndicator.setViewPager2(viewPager2)

the viewPager2 currentItem is 2
but the dotIndicator point always on first

my current version is 4.1.2

**Comment by vkotovv** [comment]
Same issue here

**Comment by vkotovv** [comment]
Related issue - #57

**Comment by utkualtas** [comment]
Same issue

**Comment by vkotovv** [comment]
@lic2050 why did you close this issue? I think it is still not resolved.

**Comment by mishalp15** [comment]
Hey here 
Any update on above issue because I'm facing same issue while using ViewPager2.
