### ISSUE TITLE
Selected dot is not updated after removing an item from ViewPager2

### ISSUE THREAD

**Issue by vkotovv** [tommybuonomo/dotsindicator#73]
For some reason, if I remove the first item from my ViewPager2, the dots count is updated, but the indicator' selected item is not updated (no dots are selected, I'm using `DotsIndicator` with different selected color). I'm calling `adapter.notifyDataSetChanged()` after removing the item. I'm expecting the first item to be selected.

What could be the issue? I'm using version 4.1.2

I also modified the sample to reproduce this bug, take a look at this branch (first DotsIndicator) - https://github.com/vkotovv/dotsindicator/tree/viewpager2-mutablelist-bug

**Comment by tommybuonomo** [comment]
Hello, thanks for your contribution !
This issue is now fixed in the new version `4.3`
Thanks 🔥
