### ISSUE TITLE
WormDotsIndicator vertical alignment is off

### ISSUE THREAD

**Issue by herrbert74** [tommybuonomo/dotsindicator#75]
Might be a duplicate of / related to #22.

When you use anything else then wrap_content for the layout_height, then the dot and the strokes are in different positions vertically. E.g. when you, like me, try to use it in a vertical ConstraintLayout chain with height = 0dp, then the strokes are at the top, while the dots are in the center.

From the code it seems, this happens because the strokes are in a LinearLayout without vertical alignment, while the dot is in a RelativeLayout and vertically centered.

My current workaround is to wrap it in a LinearLayout. You could also use a GuideLine as in the sample app, but this doesn't work for me for my situation.

Ultimately the view should be able to be placed in any layout, this needs a bit of a refactoring.

**Comment by tommybuonomo** [comment]
Could you please try with the last version ?
