### ISSUE TITLE
Infinite sliding (Repeat Indicator)

### ISSUE THREAD

**Issue by saqibsoftwares** [tommybuonomo/dotsindicator#76]
Hi, How how to set infinite sliding? I mean when the the indicator reached to the last page then the first page should be appear after that. Is it possible?

**Comment by towcar** [comment]
In my activity I have..
`public void goToFirstPage( boolean smoothScroll) {
        viewPager.setCurrentItem(0, smoothScroll);

    }`

You might need a creative solution to make this work naturally, I have a "next" button on all my pages.

**Comment by tommybuonomo** [comment]
Hello, @saqibsoftwares sorry but this will not be possible
