### ISSUE TITLE
Dots Not Updated When Using ViewPager2 + ListAdapter

### ISSUE THREAD

**Issue by cocoahero** [tommybuonomo/dotsindicator#78]
When using a `ListAdapter` with `ViewPager2`, the dots indicator does not properly respond to data changes in the adapter.

It appears that this is because only the `onChanged` callback of `AdapterDataObserver` [is implemented](https://github.com/tommybuonomo/dotsindicator/blob/master/viewpagerdotsindicator/src/main/java/com/tbuonomo/viewpagerdotsindicator/BaseDotsIndicator.kt#L241). When using a `ListAdapter`, it utilizes the much more granular callbacks of `AdapterDataObserver` instead of `onChanged`.

This appears related to #73.

**Comment by tommybuonomo** [comment]
Hello, thanks for your contribution !
This issue is now fixed in the new version `4.3`
Thanks 🔥
