### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by developerGM** [tommybuonomo/dotsindicator#8]
How can I change the background color inside the circle ?

**Comment by tommybuonomo** [comment]
Hi @developerGM, 
You can now add a stroke color to have a fill and stroke color for your dots, in version 2.1.0
Thanks for the contribution :1st_place_medal: 
Best regards !

**Comment by ergindogan** [comment]
Hey! Awesome library. I know this is already closed but I still cannot change the background inside the circle, I want it to have a fill color (for the ones that are not active). For example for the current page filled blue color and for other pages filled red color.

**Comment by tommybuonomo** [comment]
Hi @ergindogan,

First at all, thank you for your consideration :)

You can achieve something like this playing with the `dotsStrokeWidth` attribute for `SpringDotsIndicator`and `WormDotsIndicator`. Is this what you're looking for ?

![image](https://user-images.githubusercontent.com/15737675/41681545-3a8e580a-74d5-11e8-9556-7f4fa2803a14.png)

For the `WormDotsIndicator`, if the `dotsStrokeWidth` is equal to the half of the `dotsSize`, you have your desired effect.

```Xml
  <com.tbuonomo.viewpagerdotsindicator.WormDotsIndicator
      android:id="@+id/worm_dots_indicator"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:layout_marginEnd="8dp"
      android:layout_marginStart="8dp"
      android:layout_marginTop="16dp"
      app:dotsColor="@color/md_red_600"
      app:dotsStrokeColor="@color/md_red_200"
      app:dotsStrokeWidth="8dp"
      app:dotsSize="16dp"
      app:layout_constraintEnd_toEndOf="parent"
      app:layout_constraintStart_toStartOf="parent"
      app:layout_constraintTop_toBottomOf="@+id/spring_dots_indicator"
      >
  </com.tbuonomo.viewpagerdotsindicator.WormDotsIndicator>
```

**Comment by ergindogan** [comment]
Thank you for such a fast response. Using `WormDotsIndicator ` with your example fixed my issue. But for a future reference it would be nice to have this for `SpringDotsIndicator` too. When I try to use this method with  `SpringDotsIndicator`, selected page indicator becomes super small.

**Comment by tommybuonomo** [comment]
In fact, for `SpringDotsIndicator`, the inner indicator circle is inside the stroke ones.
I will modify the inner circle to fill the `dotsSize`.

Thank you for your contribution @ergindogan :blush:

**Comment by DastanIqbal** [comment]
Is it fixed, because I tried in ```SpringDotsIndicator``` its still same means dots become very small.
