### ISSUE TITLE
Indicator resets even if viewPager state restores

### ISSUE THREAD

**Issue by hbb20** [tommybuonomo/dotsindicator#86]
I am using navigation graph For fragment A->B->C->D. Fragment B has a viewPager2 where I show 3 fragments (B1, B2, B3). Works pretty well in the B during swipe interaction. 

From B3 user can go to Fragment C. If user press back from C, B comes up with B3 as a current fragment. But indicator resets to 0th index.

**Comment by tommybuonomo** [comment]
Hello, thanks for your contribution !
This issue is now fixed in the new version `4.3`
Thanks 🔥
