### ISSUE TITLE
Can't turn off clickable of dots

### ISSUE THREAD

**Issue by denbondd** [tommybuonomo/dotsindicator#87]
I want to make viewpager, where user input is disabled. And I want this dots indicator to show him where he is. But he can navigate by clicking on them. For simple tablayout I disabled every tab, but in this case this is impossible

**Comment by CsabaMiomni** [comment]
What I did using v4.1.2 is the following:

Declare the indicator within your XML file:

`<com.tbuonomo.viewpagerdotsindicator.WormDotsIndicator
         android:id="@+id/viewpager_indicator"
         android:layout_width="wrap_content"
         android:layout_height="wrap_content"
         [...]/>`

Then just set dotsClickable property to false:

`viewpagerIndicator.dotsClickable = false`

**Comment by GhimpuLucianEduard** [comment]
Also, note that the **View** also has a **isClickable** property, don't use that since it will do nothing.

Do what @CsabaMiomni suggested.

Leaving this observation here since I accidentally used **isClickable** instead of **dotsClickable**, might help other people.

**Comment by denbondd** [comment]
Thank you, now it can't be clicked. I think it should have been mentioned in README, but now it's clear))
