### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [tommybuonomo/dotsindicator#9]
All I got is this:

![image](https://user-images.githubusercontent.com/5357526/41510777-cf00ceec-7272-11e8-9846-5491daa94497.png)

**Comment by tommybuonomo** [comment]
Hi @AndroidDeveloperLB ,
You can't import the library folder as a project with AndroidStudio.
You have to import the sample folder and change the [gradle dependency](https://github.com/tommybuonomo/dotsindicator/blob/master/sample/app/build.gradle) to point to the local library path :
```Gradle
implementation project(':viewpagerdotsindicator')
```

**Comment by AndroidDeveloperLB** [comment]
I've imported it just like any other repository. Why close the issue?
I didn't import just the library or just the sample.
I've imported the entire project, and only got this.
Please fix the repository.

**Comment by tommybuonomo** [comment]
Okay I see your point ! I've re-opened the issue and i will fix this import quickly.

Thanks @AndroidDeveloperLB 👍

**Comment by tommybuonomo** [comment]
@AndroidDeveloperLB now it should be okay !

**Comment by AndroidDeveloperLB** [comment]
@tommybuonomo Now it's better. At least I got something, but it still won't build:

![image](https://user-images.githubusercontent.com/5357526/41511380-743e444c-727e-11e8-8c35-4094937da82d.png)

Why again close it?
Please try to clone the project and build it

**Comment by AndroidDeveloperLB** [comment]
For a reference, here's a sample project that I've cloned today, and worked fine:
https://github.com/rubygarage/emotion-rating-view

**Comment by tommybuonomo** [comment]
You're right @AndroidDeveloperLB :)

A properties file was missing to build the project successfully. Now all is working well by cloning the project :)
