### ISSUE TITLE
Just one question

### ISSUE THREAD

**Issue by AzathothPrimal** [tommybuonomo/dotsindicator#90]
how can I prevent page change when click on dots??
I try to disable the dots but it doesn't work

**Comment by DevJake** [comment]
Hey AzathothPrimal,

You can call `.dotsClickable = false` on your `viewpagerdotsindicator` view. In my code, I am using `spring_dot.dotsClickable = false`. 

You are likely seeking to use this to disable interaction with the viewpager + the indicator when an individual reaches a given page. Using this code (Kotlin):

```Kotlin
vpager.registerOnPageChangeCallback(object : ViewPager2.OnPageChangeCallback() {
            override fun onPageSelected(position: Int) {
                super.onPageSelected(position)

                if (position == 1){
                    vpager.isUserInputEnabled = false
                    spring_dot.dotsClickable = false
                }
            }
        })
```

Any interaction that could let the user navigate away from the 2nd page (`position == 1`) is disabled. 

Best of luck, hopefully this can be of use.

**Comment by AzathothPrimal** [comment]
Hey DevJake, totally woks! thx a lot!!
