### ISSUE TITLE
Invalid remove dots on adapter data refresh

### ISSUE THREAD

**Issue by dybuk87** [tommybuonomo/dotsindicator#93]
Hi,

I found a bug when you have for example list with 5 elements and then you change item count to for example two and trigger notifyDataSetChange()

When this is triggered I have 3 dots but it does remove the first two dots. This causes an issue that I end up with one active dot (first one active when I am no last image, and all not active for other image)

This line cause bug
https://github.com/tommybuonomo/dotsindicator/blob/ad9b4c4759bf1744914895ff6d05cb115fb2b448/viewpagerdotsindicator/src/main/java/com/tbuonomo/viewpagerdotsindicator/DotsIndicator.kt#L100

When I change it to this:
linearLayout!!.removeViewAt(linearLayout!!.childCount - 1) 

It works ok, so I think this is a valid fix for that issue

**Comment by tommybuonomo** [comment]
Hello, thanks for your contribution !
This issue is now fixed in the new version `4.3`
Thanks 🔥
