### ISSUE TITLE
Can't set `currentItem`

### ISSUE THREAD

**Issue by jonathanlinford** [tommybuonomo/dotsindicator#95]
You can set the current page in a viewPager by
```
viewPager.currentItem
```
The dots remain on the prior index until the viewpager is touched. Is there any way to set a `currentItem` on the dots indicator?

**Comment by Raingava** [comment]
Hello! The solution to this problem is in this [issue](https://github.com/tommybuonomo/dotsindicator/issues/68)

**Comment by i4guar** [comment]
I had exactly that issue with the WormDotsIndicator but know I tried the "normal" DotsIndicator and everything works as expected.

**Comment by saidmotya** [comment]
any solution for that ?

**Comment by tommybuonomo** [comment]
Duplicate of #139

**Comment by tommybuonomo** [comment]
Hello, thanks for your contribution !
This issue is now fixed in the new version `4.3`
Thanks 🔥
